[project]
name = "mcp-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.13.1",
    "ipykernel>=7.1.0",
    "ipywidgets>=8.1.8",
    "rich>=14.2.0",
]
